# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Agorasafe CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_JWT_SECRET: ${{ secrets.NEXTAUTH_JWT_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
      NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN:
        ${{ secrets.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN }}
      SITE_URL: ${{ secrets.SITE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installing dependencies
        run: npm install

      - name: Running prisma migrate deploy
        run: npx prisma migrate deploy

      - name: Running eslint linters
        run: npm run lint

      - name: Running prettier
        run: npm run prettier

      - name: Running tests
        run: npm run test:ci
